### ISSUE TITLE
Accept Duel command ids may be wrong

### ISSUE THREAD

**Issue by ahhh** [gen0cide/firescape#1]
DuelMyAccept command IDs don't seem to match on server / client command id

65 and _197_ are server side command ids to accept a duel:
See https://github.com/gen0cide-/firescape/blob/master/firescape-client/src/org/rscdaemon/client/mudclient.java#L6196#L6201

but the client sends command ids 65 and _97_ based on:
https://github.com/gen0cide-/firescape/blob/master/firescape-server/src/org/rscdaemon/server/packetbuilder/client/MiscPacketBuilder.java#L514#L521

**Comment by mmcloughlin** [comment]
+1

**Comment by gen0cide** [comment]
Where's the pull request slacker
